apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboards-service
  name: dashboards-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboards-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: dashboards-service
    spec:
      serviceAccountName: dashboards-account
      containers:
      - image: nimbleplatform/dashboards-service:IMAGE_TAG
        imagePullPolicy: Always
        name: dashboards-service
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: url
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-bot
              key: BOT_TOKEN
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: MESSAGE_HUB_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: messagehub-credentials
              key: credentials.json
#        - name: OBJECT_STORE_CREDENTIALS
#          valueFrom:
#            secretKeyRef:
#              name: object-store-credentials
#              key: credentials.json
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi