apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboards-service
  name: dashboards-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dashboards-service